//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirAsatanaTask.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        public int FlightID { get; set; }
        public string Departure { get; set; }
        public string Arrival { get; set; }
        public Nullable<System.TimeSpan> DepTime { get; set; }
        public Nullable<System.TimeSpan> ArrTime { get; set; }
        public Nullable<System.TimeSpan> Delay { get; set; }
    }
}
